In [2]:
import numpy as np

In [4]:
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [9]:
l1=[]
l2=[]
i=0
j=0
print("Enter 5 numbers into list1")
while i<5:
    l1.append(int(input()))
    i+=1
print("Enter 5 numbers into list2")
while j<5:
    l2.append(int(input()))
    j+=1
arr1 = np.array(l1)
arr2 = np.array(l2)
print("The concotenated numpy array is: ",np.concatenate((arr1,arr2)))

Enter 5 numbers into list1
1
2
3
4
5
Enter 5 numbers into list2
6
7
8
9
10
The concotenated numpy array is:  [ 1  2  3  4  5  6  7  8  9 10]


In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print("The dimensions and size of given array is:",arr.shape)

The dimensions and size of given array is: (2, 3)


In [21]:
arr = np.arange(13)
print(arr,arr.shape)
arr_2d = arr[:,np.newaxis]
print(arr_2d,arr_2d.shape)
arr_2d = arr[np.newaxis]
print(arr_2d,arr_2d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] (13,)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] (13, 1)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]] (1, 13)


In [28]:
arr1 = np.square([1,2,3,4,5])
arr2 = np.square([6,7,8,9,10])
print("Horizantal stack:")
print(np.hstack((arr1,arr2)))
print("Vertical stack:")
print(np.vstack((arr1,arr2)))

Horizantal stack:
[  1   4   9  16  25  36  49  64  81 100]
Vertical stack:
[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


In [30]:
arr = np.array([1,1,1,1,2,2,2,3,3,3,4,4,5])

unique, counts = np.unique(arr, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)

[[1 4]
 [2 3]
 [3 3]
 [4 2]
 [5 1]]
